### ISSUE TITLE
Mirroring the videos

### ISSUE THREAD

**Issue by Bonemind** [ProgrammingAgainstBrutality/end-police-violence#1]
Hey,

This is not reallly an issue but more of a tip for anyone looking to mirror these vids. Assuming you have or can install `jq`, `youtube-dl`, and `curl`:

```
curl 'https://raw.githubusercontent.com/ProgrammingAgainstBrutality/end-police-violence/master/videos.json' | jq -r '.[].source' > videos.txt && youtube-dl -i -a videos.txt -o '%(id)s.%(ext)s'
```

This'll download all videos on the site that youtube-dl knows how to download.

**Comment by ProgrammingAgainstBrutality** [comment]
Awesome! Thank you @Bonemind.

I've incorporated this info into the Readme and an additional modal on the site
