### ISSUE TITLE
Users should be able to get links to specific departments to submit complaints.

### ISSUE THREAD

**Issue by danielduffield** [ProgrammingAgainstBrutality/end-police-violence#2]
# Description
Please forgive me if this is not the appropriate place to propose a feature, but I think that the site could be improved by providing links to department complaint forms in a column adjacent to the videos in order to facilitate ease of users sending in complaints against departments shown to have acted with inappropriate force. 

I would be more than happy to open a PR request to that effect, but I figured it would be best to find out what others think of this suggestion.

**Comment by ProgrammingAgainstBrutality** [comment]
This is a great idea, @danielduffield . I've been trying to mainly keep up with adding videos as I find them. A PR would be fantastic, but I can also try to put this together when I have more time on the weekend.

**Comment by danielduffield** [comment]
I understand; there are so many videos being released that it's difficult to keep up. Let me take a pass at it today and see if I can get that taken care of with minimal changes
