### ISSUE TITLE
The site should support smaller screen sizes.

### ISSUE THREAD

**Issue by danielduffield** [ProgrammingAgainstBrutality/end-police-violence#3]
# Description
I think that the website could reach a broader audience if the site had styles that supported smaller viewports. 

My suggestion for accomplishing this would be at a tablet viewport to switch from a column layout to a stacked row layout, perhaps with dividers between entries to prevent any confusion about what video is tied to which cluster information.

I haven't completely investigated the effort required to implement this suggestion, but I imagine that it would be most easily accomplished using flex styles. Since the current app appears to use table styles, it may not be a simple change, but I would be glad to help.

**Comment by ProgrammingAgainstBrutality** [comment]
100% agree. I've added an @media that switches to a column layout at 960px or less and removed some of the extra info so it just displays the description and source under each video. Thank you for providing feedback!

**Comment by ProgrammingAgainstBrutality** [comment]
Reopening this. CSS solution only sort of works. Need to replace table setup with flexbox for more consistent solution

**Comment by ProgrammingAgainstBrutality** [comment]
Okay, switched CSS to mobile-first design and replaced the table with flex for mobile and grid for desktop.
